### ISSUE TITLE
ncurses fails to compile

### ISSUE THREAD

**Issue by unxmaal** [larb0b/irixports#1]
Running ./package.sh in ncurses/ yields this failure:

`./make_keys keys.list > init_keytry.h
/opt/local/gcc-4.7.4/bin/gcc -DHAVE_CONFIG_H -I../ncurses -I. -I../include -I/usr/people/edodd/.local/include  -D_SGI_SOURCE -DNDEBUG -std=gnu99 -g0 -O2 -mips4 --param max-inline-insns-single=1200 -c ../ncurses/comp_captab.c -o ../objects/comp_captab.o
/opt/local/gcc-4.7.4/bin/gcc -DHAVE_CONFIG_H -I../ncurses -I. -I../include -I/usr/people/edodd/.local/include  -D_SGI_SOURCE -DNDEBUG -std=gnu99 -g0 -O2 -mips4 --param max-inline-insns-single=1200 -c ../ncurses/./tinfo/init_keytry.c -o ../objects/init_keytry.o
/opt/local/gcc-4.7.4/bin/gcc -DHAVE_CONFIG_H -I../ncurses -I. -I../include -I/usr/people/edodd/.local/include  -D_SGI_SOURCE -DNDEBUG -std=gnu99 -g0 -O2 -mips4 --param max-inline-insns-single=1200 -c ../ncurses/lib_keyname.c -o ../objects/lib_keyname.o
/opt/local/gcc-4.7.4/bin/gcc -DHAVE_CONFIG_H -I../ncurses -I. -I../include -I/usr/people/edodd/.local/include  -D_SGI_SOURCE -DNDEBUG -std=gnu99 -g0 -O2 -mips4 --param max-inline-insns-single=1200 -g -DTRACE -c ../ncurses/comp_captab.c -o ../obj_g/comp_captab.o
/opt/local/gcc-4.7.4/bin/gcc -DHAVE_CONFIG_H -I../ncurses -I. -I../include -I/usr/people/edodd/.local/include  -D_SGI_SOURCE -DNDEBUG -std=gnu99 -g0 -O2 -mips4 --param max-inline-insns-single=1200 -g -DTRACE -c ../ncurses/./tinfo/init_keytry.c -o ../obj_g/init_keytry.o
/opt/local/gcc-4.7.4/bin/gcc -DHAVE_CONFIG_H -I../ncurses -I. -I../include -I/usr/people/edodd/.local/include  -D_SGI_SOURCE -DNDEBUG -std=gnu99 -g0 -O2 -mips4 --param max-inline-insns-single=1200 -g -DTRACE -c ../ncurses/lib_keyname.c -o ../obj_g/lib_keyname.o
ar cr unknown ../lib/libncurses.a ../objects/hardscroll.o ../objects/hashmap.o ../objects/lib_addch.o ../objects/lib_addstr.o ../objects/lib_beep.o ../objects/lib_bkgd.o ../objects/lib_box.o ../objects/lib_chgat.o ../objects/lib_clear.o ../objects/lib_clearok.o ../objects/lib_clrbot.o ../objects/lib_clreol.o ../objects/lib_color.o ../objects/lib_colorset.o ../objects/lib_delch.o ../objects/lib_delwin.o ../objects/lib_echo.o ../objects/lib_endwin.o ../objects/lib_erase.o ../objects/lib_flash.o ../objects/lib_gen.o ../objects/lib_getch.o ../objects/lib_getstr.o ../objects/lib_hline.o ../objects/lib_immedok.o ../objects/lib_inchstr.o ../objects/lib_initscr.o ../objects/lib_insch.o ../objects/lib_insdel.o ../objects/lib_insnstr.o ../objects/lib_instr.o ../objects/lib_isendwin.o ../objects/lib_leaveok.o ../objects/lib_mouse.o ../objects/lib_move.o ../objects/lib_mvcur.o ../objects/lib_mvwin.o ../objects/lib_newterm.o ../objects/lib_newwin.o ../objects/lib_nl.o ../objects/lib_overlay.o ../objects/lib_pad.o ../objects/lib_printw.o ../objects/lib_redrawln.o ../objects/lib_refresh.o ../objects/lib_restart.o ../objects/lib_scanw.o ../objects/lib_screen.o ../objects/lib_scroll.o ../objects/lib_scrollok.o ../objects/lib_scrreg.o ../objects/lib_set_term.o ../objects/lib_slk.o ../objects/lib_slkatr_set.o ../objects/lib_slkatrof.o ../objects/lib_slkatron.o ../objects/lib_slkatrset.o ../objects/lib_slkattr.o ../objects/lib_slkclear.o ../objects/lib_slkcolor.o ../objects/lib_slkinit.o ../objects/lib_slklab.o ../objects/lib_slkrefr.o ../objects/lib_slkset.o ../objects/lib_slktouch.o ../objects/lib_touch.o ../objects/lib_tstp.o ../objects/lib_ungetch.o ../objects/lib_vidattr.o ../objects/lib_vline.o ../objects/lib_wattroff.o ../objects/lib_wattron.o ../objects/lib_winch.o ../objects/lib_window.o ../objects/nc_panel.o ../objects/safe_sprintf.o ../objects/tty_update.o ../objects/varargs.o ../objects/vsscanf.o ../objects/lib_freeall.o ../objects/expanded.o ../objects/legacy_coding.o ../objects/lib_dft_fgbg.o ../objects/lib_print.o ../objects/new_pair.o ../objects/resizeterm.o ../objects/use_screen.o ../objects/use_window.o ../objects/wresize.o ../objects/access.o ../objects/add_tries.o ../objects/alloc_ttype.o ../objects/codes.o ../objects/comp_captab.o ../objects/comp_error.o ../objects/comp_hash.o ../objects/db_iterator.o ../objects/doalloc.o ../objects/entries.o ../objects/fallback.o ../objects/free_ttype.o ../objects/getenv_num.o ../objects/home_terminfo.o ../objects/init_keytry.o ../objects/lib_acs.o ../objects/lib_baudrate.o ../objects/lib_cur_term.o ../objects/lib_data.o ../objects/lib_has_cap.o ../objects/lib_kernel.o ../objects/lib_keyname.o ../objects/lib_longname.o ../objects/lib_napms.o ../objects/lib_options.o ../objects/lib_raw.o ../objects/lib_setup.o ../objects/lib_termcap.o ../objects/lib_termname.o ../objects/lib_tgoto.o ../objects/lib_ti.o ../objects/lib_tparm.o ../objects/lib_tputs.o ../objects/lib_trace.o ../objects/lib_ttyflags.o ../objects/lib_twait.o ../objects/name_match.o ../objects/names.o ../objects/obsolete.o ../objects/read_entry.o ../objects/read_termcap.o ../objects/strings.o ../objects/tries.o ../objects/trim_sgr0.o ../objects/unctrl.o ../objects/visbuf.o ../objects/alloc_entry.o ../objects/captoinfo.o ../objects/comp_expand.o ../objects/comp_parse.o ../objects/comp_scan.o ../objects/parse_entry.o ../objects/write_entry.o ../objects/define_key.o ../objects/hashed_db.o ../objects/key_defined.o ../objects/keybound.o ../objects/keyok.o ../objects/version.o
ar: ../lib/libncurses.a: No such file or directory
gmake[1]: *** [Makefile:860: ../lib/libncurses.a] Error 1
gmake[1]: *** Waiting for unfinished jobs....
gmake[1]: Leaving directory '/usr/people/edodd/projects/github/unxmaal/irixports/ncurses/ncurses-6.1/ncurses'
gmake: *** [Makefile:115: all] Error 2`

**Comment by larb0b** [comment]
I am not able to reproduce this. Has your ncurses package.sh been modified, have you run bootstrap.sh, etc.?

**Comment by unxmaal** [comment]
I've run bootstrap.sh, and then run ./package.sh from ncurses/.

FWIW I am sourcing this to set my env:

```_cdir="gcc-8.2.0"
export CC=/opt/local/$_cdir/bin/gcc
export CXX=/opt/local/$_cdir/bin/gcc
export CFLAGS="-std=gnu99 -g0 -O2 -mips4"
export CPPFLAGS="-D_POSIX90"
export CXXFLAGS="-g0 -O2 -mips4"
export LDFLAGS=" -L/usr/local/lib -L/usr/local/lib32"
export LD_LIBRARY_PATH=/opt/local/curl/lib:/opt/local/expat/lib:/opt/local/berkeley-db/lib:/opt/local/gmp/lib:/opt/local/mpc/lib:/opt/local/mpfr:/lib:/opt/local/mpfr/lib:/opt/local/$_cdir/lib32:/opt/local/$_cdir/lib
export LIBRARY_PATH=$LD_LIBRARY_PATH
export LD_LIBRARYN32_PATH=$LD_LIBRARY_PATH

export AR=ar
export ARFLAGS=cr
export AR_FLAGS=cr
```

**Comment by larb0b** [comment]
Hm... please pull and try again. I think it might work now.

**Comment by unxmaal** [comment]
My apologies:

I removed the AR env params from my environment, and re-ran ./package.sh, and it works now.
