### ISSUE TITLE
irixports should have an internal script to gather env settings for use in troubleshooting

### ISSUE THREAD

**Issue by unxmaal** [larb0b/irixports#2]
irixports should have an internal script to gather env settings for use in troubleshooting.

For example:

./package.sh trouble
 ...
 Trouble report generated as trouble.txt. Please paste its contents into a github issue.

**Comment by larb0b** [comment]
Could you go into more detail as to what you mean by this (e.g. what exactly should be collected)?

**Comment by unxmaal** [comment]
Perhaps:
hinv > trouble.txt
env >> trouble.txt

Might want to strip some bits out.

**Comment by larb0b** [comment]
This might be something nice for the future as it becomes more necessary, but for now I can just ask for the output of `hinv`/`env` when needed.
