### ISSUE TITLE
irixports fails looking for mksh, which is absent if the user fails to run bootstrap.sh first

### ISSUE THREAD

**Issue by unxmaal** [larb0b/irixports#3]
irixports fails looking for mksh, which is absent if the user fails to run bootstrap.sh first.

**Comment by larb0b** [comment]
`If you've never used irixports on the system, run bootstrap.sh as root to bootstrap some necessary tools.`

It is stated in the README that bootstrap.sh needs to be run first if you haven't used irixports on the system before.
